---
Default Meta Description: manticore description
Default Meta Tags: manticore, default, tags
Name: Care Plus Group Intranet
Email: paul@eskimosoup.co.uk
Twitter: https://twitter.com/careplusgroup
Facebook: https://www.facebook.com/careplusgroup
Telephone: 01472 266999
Address: Care Plus Group, Cleethorpe Road, Grimsby, North East Lincolnshire, DN31
  3LL
Report Email: paul@eskimosoup.co.uk
Award Email: paul@eskimosoup.co.uk
Report Facilities Emails: paul@eskimosoup.co.uk, ade@eskimosoup.co.uk, james@eskimosoup.co.uk
Suggestion Email: paul@eskimosoup.co.uk
Document Store: Q:\
Foundations Document Store: T:\
